# Generated by Django 3.2.8 on 2023-04-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SplitwiseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('splitwise_user_id', models.CharField(max_length=256)),
                ('bank_transaction_id', models.CharField(max_length=256)),
                ('bank_transaction_time', models.DateTimeField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('splitwise_transaction_id', models.CharField(max_length=256)),
                ('splitwise_group_id', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
