# Generated by Django 3.2.8 on 2023-04-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitwisetransaction',
            name='bank_transaction_desc',
            field=models.CharField(default='ds', max_length=256),
            preserve_default=False,
        ),
    ]
