# Generated by Django 3.2.8 on 2023-04-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_api', '0002_splitwisetransaction_bank_transaction_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitwisetransaction',
            name='splitwise_transaction_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
