# Generated by Django 3.2.8 on 2023-12-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise_api', '0004_auto_20231208_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='splitwisetransaction',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
